server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: zari-service
              uri: http://localhost:9005
              predicates:
                - Path=/zari/**

            - id: noti-service
              uri: http://localhost:8099
              predicates:
                - Path=/noti/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
