server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true            # Cho phép định tuyến động theo tên service
              lower-case-service-id: true # Tự chuyển serviceId về lowercase để khớp URI

          routes:
            - id: zari-service
              uri: lb://zari-service
              predicates:
                - Path=/zari/**

            - id: task-service
              uri: lb://task-service
              predicates:
                - Path=/task/**

            - id: noti-service
              uri: lb://noti-service
              predicates:
                - Path=/noti/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
